CREATE DATABASE JEDI;
USE JEDI;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	USERID VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    PRIMARY KEY(USERID)
);

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT(
	USERID VARCHAR(255) NOT NULL,
	ROLLNO VARCHAR(255) UNIQUE NOT NULL,
    DEPARTMENT VARCHAR(255) NOT NULL,
    ISAPPROVED BOOLEAN NOT NULL,
    PRIMARY KEY(ROLLNO),
    FOREIGN KEY (USERID) REFERENCES USER(USERID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PERSONALDETAILS;
CREATE TABLE PERSONALDETAILS(
	NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    ADDRESS TEXT,
    USERID VARCHAR(255) PRIMARY KEY,
    FOREIGN KEY (USERID) REFERENCES USER(USERID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PROFESSOR;
CREATE TABLE PROFESSOR (
  USERID varchar(255) PRIMARY KEY,
  DEPARTMENT varchar(255) default NULL,
  CONSTRAINT USERID FOREIGN KEY (USERID) REFERENCES USER(USERID) ON DELETE CASCADE ON UPDATE CASCADE
) ;

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE(
	CID VARCHAR(255) PRIMARY KEY,
    COURSENAME VARCHAR(255) NOT NULL,
    PROFESSORID VARCHAR(255),
    FOREIGN KEY (PROFESSORID) REFERENCES PROFESSOR(USERID) ON DELETE SET NULL
);

DROP TABLE IF EXISTS CATALOG;
CREATE TABLE CATALOG(
	CATALOGID VARCHAR(10) PRIMARY KEY,
    CID VARCHAR(255),
    FOREIGN KEY (CID) REFERENCES COURSE(CID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS SEMESTERREGISTRATION;
CREATE TABLE SEMESTERREGISTRATION(
	ROLLNO VARCHAR(255),
    CID VARCHAR(255),
    SEMESTER INT(2),
    GRADE VARCHAR(255),
    FOREIGN KEY(CID) REFERENCES COURSE(CID) ON DELETE SET NULL
);

DROP TABLE IF EXISTS NOTIFICATION;
CREATE TABLE NOTIFICATION(
	NOTIFID VARCHAR(255) PRIMARY KEY,
    ROLLNO VARCHAR(255),
    MESSAGE TEXT,
    FOREIGN KEY (ROLLNO) REFERENCES STUDENT(ROLLNO)
);

DROP TABLE IF EXISTS GRADECARD;
CREATE TABLE GRADECARD(
	ROLLNO VARCHAR(255) PRIMARY KEY,
    CPI FLOAT(4,0),
    SEMESTER INT(2),
    FOREIGN KEY (ROLLNO) REFERENCES STUDENT(ROLLNO) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE PAYMENT(
	TRANSID VARCHAR(255) PRIMARY KEY,
    PAYMODE VARCHAR(255),
    AMOUNT LONG,
    PAYSTATUS VARCHAR(255)
);
